### PR TITLE
JAPI-150 Added missing file

### PR DESCRIPTION
**Pull request by jpmcmu**
Signed-off-by: James McMullan <James.McMullan@lexisnexis.com>

## Type of change:
- [X] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [X] I have created a corresponding JIRA ticket for this submission
- [X] My code follows the code style of this project.
  - [X] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [ ] The change has been fully tested:
  - [ ] I have performed unit tests to cover my changes.
  - [ ] I have performed system test and covered possible regressions and side effects.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.

### CODE REVIEW

**Comment by jpmcmu** [comment]
@Michael-Gardner please review

**Comment by Michael-Gardner** [comment]
@jpmcmu Please update the year on the copywrite and I'll go ahead and merge it.

**Comment by jpmcmu** [comment]
@Michael-Gardner updated

**Comment by Michael-Gardner** [comment]
@jpmcmu can we make the test here that requires a connection to a local server optional?  our deployment process does the test objective, but it will always fail on this one because we don't have the connection.

**Comment by jpmcmu** [comment]
@Michael-Gardner added a RemoteTests category and excluded it by default. Please review

**Comment by Michael-Gardner** [comment]
Thanks James, checking it out now.

**Pull request merged**
