### PR TITLE
JAPI-163- HPCCFileSprayClient largeFileUpload truncated files at 16384 bytes

### PR DESCRIPTION
**Pull request by jchambers-ln**
## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [x] I have created a corresponding JIRA ticket for this submission
- [x] My code follows the code style of this project.
  - [x] I have applied the Eclipse code-format template provided. (didn't use eclipse but it should match)
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [ ] The change has been fully tested:
  - [ ] I have performed unit tests to cover my changes.
  - [ ] I have performed system test and covered possible regressions and side effects.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.

## Testing:

Tested with a 215mb file and the full file was transfered, before you only got 16384 bytes of the file (16*buffer).

### CODE REVIEW

**Comment by rpastrana** [comment]
@jchambers-ln do we want this change in the 7.2 stream?

**Comment by jchambers-ln** [comment]
Wasn't sure where your active development is.  I tested this on a branch based off the 7.2.0 branch so it can be pulled there also.  But yes if we can roll it to that branch that would be good.  Let me know if you want me to change the pull to a different branch.

**Comment by rpastrana** [comment]
looks good

**Comment by rpastrana** [comment]
@Michael-Gardner  let's make sure this gets merged on to 7.2.x

**Pull request merged**
