### PR TITLE
HPCC-JAPIs-61 Implement SFTP stop using WS to upload files

### PR DESCRIPTION
**Pull request by rpastrana**
- Add JSCH dependancy
- Add SFTP utility class
- Implement SFTP to HPCC Landing Zone method
- Add new helper methods in filespray which utilze sftp to upload files
- Add new helper method in wsclient to make use of filespray methods
- Updated README

Signed-off-by: rpastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@drealeed plese take a detailed look at this change which utilizes sftp for data file transfers.

**Comment by drealeed** [comment]
very nice, looks good

**Comment by rpastrana** [comment]
@jchambers-ln file uploading via web services has been removed in favor of a SFTP approach. 
Drea already looked at the code change but thought you might be able to provide further insight. Please review and comment.

**Comment by jchambers-ln** [comment]
The SFTP is the best option, however a thought occurs to me, but not related to HIPIE/RAMPS/DSP -- there are cases when users don't have SFTP access but could upload via http, I'm not sure if you want to completely remove "uploading via web services" long term.

I did a quick review of the code and it looks good.

**Comment by rpastrana** [comment]
I hear you, my concern is abuse of the WS based upload. I'll add them back in, but will add size restrictions...

**Comment by rpastrana** [comment]
@jchambers-ln please take a look.

**Comment by jchambers-ln** [comment]
looks good to me

**Pull request merged**
