### PR TITLE
JAPI-00096 Expose file part information

### PR DESCRIPTION
**Pull request by johnholt**
Modified FileDetailInfo class to produce a by cluster array of File Part metadata containers.

Added a wrapper class for the cluster file part metadata container.

Added a wrapper class for the file part metadata.

Added logic to PlatformTester class to show file part information for one of the test files.

Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [x ] I have created a corresponding JIRA ticket for this submission
- [x ] My code follows the code style of this project.
  - [x ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x ] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [ ] The change has been fully tested:
  - [ x] I have performed unit tests to cover my changes.
  - [ ] I have performed system test and covered possible regressions and side effects.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x ] I have given due consideration to all of the following potential concerns:
  - [x ] Scalability
  - [ x] Performance
  - [x ] Security
  - [x ] Thread-safety
  - [x ] Premature optimization
  - [x ] Existing deployed queries will not be broken
  - [x ] This change fixes the problem, not just the symptom
  - [x ] The target branch of this pull request is appropriate for such a change.

## Testing:

A test client was created that produced the appropriate file part information

### CODE REVIEW

**Comment by johnholt** [comment]
@rpastrana  @Michael-Gardner  Please review.  This should be releasable at any time.  It will be used by the Spark integration project.

**Comment by Michael-Gardner** [comment]
Thanks,  I'll go ahead and take a look at it today and get some feedback to you.

**Comment by Michael-Gardner** [comment]
@johnholt I looked it over and it looks great.  Are the unit tests that you did something that we could roll into the tests for wsclient?

**Comment by johnholt** [comment]
@Michael-Gardner   I can add them to test.  Is there any particular class that you would like to have them, or should they be a stand alone test?

**Comment by Michael-Gardner** [comment]
Either as your own stand alone test class or to the PlatformTester.  Whichever is easiest for you.

**Comment by johnholt** [comment]
@Michael-Gardner  @rpastrana  Added test to PlatformTester class to show file part information for one of the test files.

**Comment by Michael-Gardner** [comment]
Awesome thanks John.  Looks great.

**Pull request merged**
