### PR TITLE
JAPI-90 : new wsCreateOrUpdateAttributes method

### PR DESCRIPTION
**Pull request by drealeed**
Fix for JAPI-90: a new method, wsCreateOrUpdateAttribute, to help improve performance of adding attributes to a repo.

I pointed HIPIE to the method and called it to both create and to update attributes. It worked fine.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [x] I have created a corresponding JIRA ticket for this submission
- [x] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [x] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [ ] The change has been fully tested:
  - [ ] I have performed unit tests to cover my changes.
  - [x] I have performed system test and covered possible regressions and side effects.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.

### CODE REVIEW

**Comment by rpastrana** [comment]
@drealeed is this ready for code review?

**Comment by drealeed** [comment]
Yes, all ready. I'm not sure why the pom.xml update; it looks like master's already at 1.3.0-SNAPSHOT, but even resetting that file to master and pushing it to this branch didn't change that diff.

**Comment by rpastrana** [comment]
@drealeed can you manually change the version on that file to 1.3.0-SNAPSHOT ? or amend the change and un-stage that particular file?

**Comment by drealeed** [comment]
I've tried several things but still get that wierd diff showing up. I've done a hard reset of the pom.xml file to what' sin master, and it does show up as 1.3.0-SNAPSHOT, but for some reason the diff is still saying that the existing version in the master branch pom file is 1.2.0.

Oh well. I'll close this pr, create a new branch, paste my one change in it and pull that.

**Pull request closed without merging**
