### PR TITLE
Japi-101 wuquery refactor

### PR DESCRIPTION
**Pull request by drealeed**
This PR turned out to be more complicated than expected.

The heart of it is wrapping WUQuery as a WUQueryInfo object passed in for searching workunits. I took advantage of java to lock down the types of things like startDate and endDate, and poked through the platform code to figure out enums for the sort by field.  During testing I found that a lot of fields were being ignored, so after a chat with Kevin Wang, I removed the properties (before, after, etc) that are no longer being used.   The class is fully javadoc-documented for later reference.

It has a validate() method that checks that all app values have an application/name/value. calling WUQueryInfo.getRaw() returns the latest soap WUQuery object. calling WUQueryInfo.getRaw156(appvaluenum) returns a WUQuery 1_56 object, with the single appvalue fields populated by the respective item in ApplicationValues. This is what's used for the fallback workunit appval search.

I found while switching out WUQuery with WUQueryInfo that there were a few workunit search methods that had a lot of duplicate code. I refactored the getWorkunits-type methods into a smaller set. I also found a few places still returning a WUWorkunitsResponse and switched those out with WorkunitInfo/list of workunitinfo where appropriate.

 I also created a BaseWsWorkunitsClientIntegrationTest that tests workunit creation/searching/deletion/etc.. It's extended by a WsWorkunitsClientIntegrationTest_620 that sets the platform info to a 6.2.0 cluster. If you ever want to run this test against a later version of a cluster, you can copy the 620 file and use it as the template for testing against other clusters.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [x] This change is a breaking change (fix or feature that will cause existing behavior to change).

## Checklist:
- [x] I have created a corresponding JIRA ticket for this submission
- [x] My code follows the code style of this project.
  - [ ] I have applied the Eclipse code-format template provided.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [x] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [x] The change has been fully tested:
  - [x] I have performed unit tests to cover my changes.
  - [x] I have performed system test and covered possible regressions and side effects.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.

### CODE REVIEW

**Comment by drealeed** [comment]
@Michael-Gardner I created a new 5.4 integration test and ran the tests against the baird cluster. all tests passed, including the search by multiple application values & single application value test.

**Comment by Michael-Gardner** [comment]
@drealeed Not sure if you're working off the most recent master.   It looks like you have committed some old README changes that Rodrigo modified the other day.

**Comment by drealeed** [comment]
Sorry about the readme thing, that was a merge error. Fixed it.

**Comment by drealeed** [comment]
I have japi-103 (bulk createAndUpdateAttributes) ready to go when this one's pulled. It includes an integration test for wsAttributesClient. The new method is substantially faster:

Time to individually create 32 attributes with checkout/checkin:114593 (150 soap service calls calls)
Time to individually update 32 existing attributes with checkout/checkin:98060 (150 soap service calls)

Time to bulk create 32 attributes with checkout/checkin:34880 (36 soap service calls)
Time to bulk update 32 existing attributes with checkout/checkin:9139 (4 soap service calls)

**Comment by Michael-Gardner** [comment]
@drealeed it says there are 16 files touched by this PR and several of them are so large that the diff for github won't show all the changes.  Are you sure there aren't any more issues w/ the base of this PR?

**Comment by drealeed** [comment]
I just rechecked, and it all looks good. Of the three files that are so large the diff doesn't show by default, HPCCWsWorkunitsClient is where all the real work is. The other two are pojos used/updated by the new feature. Six of the files in question are part of the new integration test stuff.

**Comment by Michael-Gardner** [comment]
@drealeed I took a look at this over the weekend and it looks fine, I'm going to do some quick testing this morning before I merge.  But if everything goes well it looks like we'll get a new snapshot out this afternoon.

**Pull request merged**
