### PR TITLE
Handle getFileData for child datasets

### PR DESCRIPTION
**Pull request by dhanasiddharth**
When a logical file has child datasets, getting all *row*s includes child dataset rows as well. `getChildNodes` returns correct set of rows

### CODE REVIEW

**Comment by rpastrana** [comment]
@drealeed do you mind doing a quick code review of this change?
@dhanasiddharth can you open a corresponding JIRA issue for this (https://track.hpccsystems.com/secure/Dashboard.jspa)?

**Comment by rpastrana** [comment]
@Michael-Gardner FYI

**Comment by dhanasiddharth** [comment]
Created a ticket https://track.hpccsystems.com/browse/JAPI-29

**Comment by drealeed** [comment]
this is the right way to do it--looks good to me. I'm in the UK this week, sorry for the delay.

**Pull request merged**
